### ISSUE TITLE
Patching fails for non 'object' value type dictionaries

### ISSUE THREAD

**Issue by tillig** [aspnet/JsonPatch#33]
Given a model like this:

```csharp
public class DemoModel
{
  public DemoModel()
  {
    this.Numbers = new Dictionary<string, int>();
  }

  public IDictionary<string, int> Numbers { get; private set; }
}
```

When JSON serialized, the object looks like this:

```json
{
  "Numbers": {
    "one":1,
    "two":2
  }
}
```

If I try to create a patch document and apply it, it fails:

```csharp
[Fact]
public void DictionaryTest()
{
  var model = new DemoModel();
  model.Numbers["one"] = 1;
  model.Numbers["two"] = 2;

  var patch = new JsonPatchDocument();
  patch.Operations.Add(new Operation("add", "/Numbers/three", null, 3));
  patch.ApplyTo(model);

  Assert.Equal(3, model.Numbers.Count);
  Assert.Equal(1, model.Numbers["one"]);
  Assert.Equal(2, model.Numbers["two"]);
  Assert.Equal(3, model.Numbers["three"]);
}
```

The test fails on the `patch.ApplyTo(model)` line:

```
at Microsoft.AspNetCore.JsonPatch.Helpers.ObjectTreeAnalysisResult..ctor(Object objectToSearch, String propertyPath, IContractResolver contractResolver)
   at Microsoft.AspNetCore.JsonPatch.Adapters.ObjectAdapter.Add(String path, Object value, Object objectToApplyTo, Operation operationToReport)
   at Microsoft.AspNetCore.JsonPatch.Adapters.ObjectAdapter.Add(Operation operation, Object objectToApplyTo)
   at Microsoft.AspNetCore.JsonPatch.JsonPatchDocument.ApplyTo(Object objectToApplyTo, IObjectAdapter adapter)
   at DemoProject.DictionaryTest() in C:\path\to\Fixture.cs:line 73
Result Message:	Unable to cast object of type 'Newtonsoft.Json.Serialization.JsonDictionaryContract' to type 'Newtonsoft.Json.Serialization.JsonObjectContract'.
```

Is this a known issue? Or is there a workaround?

**Comment by tillig** [comment]
I found a sort of complicated workaround by having a model specifically for use by the patch operation and using AutoMapper to map `ExpandoObject` to dictionary. If I remove the AutoMapper code, it boils down to this:

```csharp
public class DemoPatchModel
{
  public dynamic Numbers { get; private set; } = new ExpandoObject();
}

public class DemoModel
{
  public IDictionary<string, int> Numbers { get; private set; } = new Dictionary<string, int>();
}

[Fact]
public void DictionaryTest()
{
  var model = new DemoModel();
  model.Numbers["one"] = 1;
  model.Numbers["two"] = 2;

  var patchModel = new DemoPatchModel();
  var numbersDictionary = (IDictionary<string, object>)patchModel.Numbers;
  foreach(var pair in model.Numbers)
  {
    numbersDictionary[pair.Key] = pair.Value;
  }

  var patch = new JsonPatchDocument();
  patch.Operations.Add(new Operation("add", "/Numbers/three", null, 3));
  patch.Operations.Add(new Operation("remove", "/Numbers/one", null));
  patch.ApplyTo(patchModel);

  model.Numbers.Clear();
  foreach (var pair in numbersDictionary)
  {
    model.Numbers[pair.Key] = (int)pair.Value;
  }

  Assert.Equal(2, model.Numbers.Count);
  Assert.Equal(2, model.Numbers["two"]);
  Assert.Equal(3, model.Numbers["three"]);
}
```

The use of `ExpandoObject` lets you have that dictionary but gets around the JSON contract type mismatch.

**Comment by Eilon** [comment]
@kichalla can you look and see if this is something we could just easily add support for?

**Comment by sandorfr** [comment]
Painful bug it is :) Thanks for the workaround.
